config/routes.rb
Rails.application.routes.draw do
devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  namespace :admin do
  	resources :email, only: [:new, :create]
  end
 	get "terms" => 'page#terms', :as => :terms
	root 'page#index'
	resources :page, only: [:index, :new, :create,:terms]
	#resources :bookings, only: [:new, :create]

  match "*path", to: "errors#not_found", via: :all
    match "*path", to: "errors#internal_server_error", via: :all
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookable_item.rb
class BookableItem < ApplicationRecord
	belongs_to :booking
	belongs_to :removable_item

	attr_accessor :enable
	
end

app/models/booking.rb
class Booking < ApplicationRecord
	has_many :bookable_items, dependent: :destroy, class_name: 'BookableItem'
	has_many :removable_items, through: :bookable_items
	

  has_one :quotation
  
	accepts_nested_attributes_for :bookable_items, :allow_destroy => true
  accepts_nested_attributes_for :quotation, :allow_destroy => false

  #after_create :set_status

	enum status: {issue_a_quote: 0,sent_and_pending: 1,accepted: 2}

#https://stackoverflow.com/questions/9174513/rails-has-many-through-form-with-checkboxes-and-extra-field-in-the-join-model

	def initialized_removable_items # this is the key method
    [].tap do |o|
      RemovableItem.all.each do |removable_item|
        if c = bookable_items.find { |c| c.removable_item_id == removable_item.id }
          o << c.tap { |c| c.enable ||= true }
        else
          o << BookableItem.new(removable_item: removable_item)
        end
      end
    end
  end

  def quotations
     Quotation.where(booking_id: id)
  end
  

end

app/models/email.rb
class Email < MailForm::Base
	attribute :name,      :validate => true
  attribute :phone,      :validate => true
  attribute :post_code,      :validate => true
  attribute :email,     :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i

  attribute :message
  attribute :nickname,  :captcha  => true


  def headers
    {
      :subject => "Free quotation Request or Callback !",
      :to => "quote@rdlway.com",
      :from => %("#{name}" <#{email}>)
    }
  end
 
end

app/models/page.rb
class Page < MailForm::Base

 

	attribute :name,      :validate => true
  attribute :phone,      :validate => true
  attribute :post_code,      :validate => true
  attribute :email,     :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i

  attribute :message
  attribute :nickname,  :captcha  => true


  def headers
    {
      :subject => "Free quotation Request",
      :to => "roshiend@gmail.com",
      :from => %("#{name}" <#{email}>)
    }
  end
 
end

app/models/quotation.rb
class Quotation < ApplicationRecord
	belongs_to :booking
	enum status: [ :sent_and_pending,:accepted,:issue_a_quote ]

	monetize :price_cents,:numericality => {:greater_than => 0}
end

app/models/removable_item.rb
class RemovableItem < ApplicationRecord
  has_many :bookable_items
  has_many :bookings, through: :bookable_items
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :process_bookable_item_attrs, only: [:create, :update]
  def new
  	@booking = Booking.new
   
  end

  def create
    @booking = Booking.new(booking_params)
     	
  	if @booking.save
  		redirect_to root_path
  	else
  		render :new
      
  	end
  end



  def process_bookable_item_attrs
    params[:booking][:bookable_items_attributes].values.each do |cat_attr|
      cat_attr[:_destroy] = true if cat_attr[:enable] != '1'
    end
  end

  private
  	def booking_params
  		params.require(:booking).permit(:person_name,:post_code,
  		:address,:valid_telephone_number,:email,removable_item_ids:[],bookable_items_attributes:[:bookable_item_qty, :booking_id, :removable_item_id, :_destroy,:enable]	)
  	end

end

app/controllers/errors_controller.rb
class ErrorsController < ApplicationController
  def not_found
    redirect_to root_path
  end

  def internal_server_error
    redirect_to  root_path
  end
end

app/controllers/page_controller.rb
class PageController < ApplicationController
  def index
  	@contact = Page.new(params[:page])
    set_meta_tags og:{
      title: "R D L Removals",
      description:"Your Local House Removing Partner",
      keywords: "near me, house rent, house rent near me, chester, west-midlands, stoke-on-trent, stoke, cheap , affordable, rent a car, house removals chester, house removals stoke-on-trent, house removals, house removals costs, house removal companies, house removals london, house removal boxes, house removal costs uk, man with van, man with van london, manwith man stoke-on-trent, man with van chester,man with van near me, man with van hire, man with van delivery service, man with van courier, man with van courier uk",
      url: "https://www.rdlway.com",
      image: "https://www.rdlway.com/assets/van-69b5822dbf42fd16902a0323fe50f07363ec82af4c67c58c6acfbc115b1ebf31.png",
      type:"website"
    },
    fb:{app_id: "459724851566905"}



    #meta tags added for facebook
    
  end

  def new
  	
  end

  def create
    
  	@contact = Page.new(params[:page])
    @contact.request = request
    respond_to do |format|
      if @contact.deliver
        # re-initialize Home object for cleared form
        @contact = Page.new
        format.html { render 'index'}
        format.js   { flash.now[:success] = @message = "Thank you for your request. One of our team member will contact you soon" }
      #working code uncomment whenever need
      #------------------------------------- 

        # begin
        #  #get predefine message as well as can genereate dynamicly based on requirements
        # TwilioClient.send_message(message)
        #   puts "-- Text Message sent! --"
        # rescue Twilio::REST::TwilioError => error
        #   p error.message
          
        # end

      else
        format.html { render 'page/contact' }
        format.js   { flash.now[:error] = @message = "Something went wrong, Please try again" }
      end
    end
  end

  def terms
    respond_to do |format|
      format.html
      format.js
    end
  end

  private
  def message
    "New Qoutation Request, Please Check your E-mails"
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/booking_request_helper.rb
module BookingRequestHelper
end

app/helpers/errors_helper.rb
module ErrorsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/admin/bookings/_form.html.erb
<%=semantic_form_for [:admin, @booking] do |f| %>
  <%=f.semantic_errors *f.object.errors.keys%>
	  <%=f.inputs "Person Information", :class =>"contact-info-booking-admin" do %>
	  	<%= f.input :title, :as => :select, :collection => [["Mr", "Mr"],["Mrs", "Mrs"],["Other", "Other"]],:input_html => { :require =>true} %>
			<%= f.input :person_name,:input_html => { :require =>true}%>
			<%= f.input :email,:input_html => { :require =>true}%>
			<%= f.input :valid_telephone_number,:input_html => { :require =>true}%>
		

		<%=f.inputs "Current Address", :class =>"address-current-panel-admin-frm" do %>
			
			<%= f.input :current_house_name_or_number,:label => "house number/Name",:input_html => { :require =>true}%>
			<%= f.input :current_street_name,:input_html => { :require =>true}%>
			<%= f.input :current_post_code,:input_html => { :require =>true}%>
		<%end%>	

		<%=f.inputs "New Address", :class =>"address-current-panel-admin-frm admin-frm-from-booking"  do %>
			<%= f.input :new_house_name_or_number,:input_html => { :require =>true}%>
			<%= f.input :new_street_name,:input_html => { :require =>true}%>
			<%= f.input :new_post_code,:input_html => { :require =>true}%>
		<%end%>
		
	<%end%>	

	 
		
		<%=f.inputs "I want to Move these...", :class =>"contact-info-booking-want-to-move-admin" do %>
			<%= f.fields_for :bookable_items, @booking.initialized_removable_items do |b| %>
			<div class="grid_4">
				<% removable_item = b.object.removable_item %>
		    <%= b.hidden_field :removable_item_id %>
				<%= b.check_box :enable %>
		    <%= b.label :enable, removable_item.item_name %>
		    <%=b.select :bookable_item_qty, (1..10) %>
			</div>
				
		  <%end%>
		<%end%>	
			
		<%=f.inputs "Removale Schedule ", :class =>"contact-info-booking-want-to-move-admin" do %>
			 <%#= f.input :expected_removal_day,:as => :string, :input_html => {:class => 'datepicker hasDatePicker'}%>
				<div id="removal_day"></div>
		  	<%=f.input :expected_removal_day,  as: :hidden%>
		  	
		<%end%>	

	 
	  <%=f.actions :submit, :cancel %>
<%end%>

<script>
  $( function() {
    $( "#removal_day" ).datepicker({
    	minDate: 0,
    	altField: "#booking_expected_removal_day",
      altFormat: "DD, d MM, yy"
    });
  } );


  </script>


   

app/views/admin/bookings/quotations/_form.html.erb
<%=semantic_form_for [:admin, @booking,@quotation] do |f| %>
  <%=f.semantic_errors *f.object.errors.keys%>
	<div class="container">
		 Dear <%=@booking.person_name%>,
		<br><br>	
		
  	  <h4>
  	  	Thank you for your interest in using the RDL Transportation Removal Service for your forthcoming move.   	  	Your move is from <strong class "red_p_code"><%=@booking.current_post_code%></strong> 
  	  	to <strong class "red_p_code"><%=@booking.new_post_code%></strong>.
  	  </h4> 
		<br>
		<%=f.input :price,:input_html => { :require =>true} %> <br>
		<%= f.input :vechile_type, :as => :select, :collection => [[" 3.5T 14feet Mercedes Luton ", " 3.5T 14feet Mercedes Luton "],["Sprinter", "Sprinter"]],:input_html => { :require =>true} %>
		<br>
		<%= f.input :team_members, :as => :select, :collection => [[" 2 man removal team  ", " 2 man removal team  "],["3 man removal team ", "3 man removal team "]],:input_html => { :require =>true} %>
		to move 
		<%= f.input :house_flat_type, :as => :select, :collection => [["  2 bed room house  ", " 2 bed room house  "],[" 3 bed room house ", " 3 bed room house "]],:input_html => { :require =>true} %>
  	 
 
	  <%= f.input :customer_name, :input_html => { :value => f.object.booking.person_name },  as: :hidden%>
	  <%= f.input :from_address, :input_html => { :value => f.object.booking.current_post_code },  as: :hidden%>
	  <%= f.input :to_address, :input_html => { :value => f.object.booking.new_post_code },  as: :hidden%>
  
  <div class="div-action">
  	<%=f.actions :submit, :cancel %>
  </div>

  
<%end%>



   

app/views/admin/bookings/quotations/quotation.pdf.erb
<!DOCTYPE html>
<html>
	<head>
		<title>
			
		</title>
	</head>
	<body>
		<h3>R D L Transportation</h3>
	</body>
</html>

app/views/bookings/create.html.erb
<h1>BookingRequest#create</h1>
<p>Find me in app/views/booking_request/create.html.erb</p>

app/views/bookings/new.html.erb
<div class="new-booking-request-section">
	<div class="container">
		<%=form_for @booking  do |f|%>
			
			<%=f.text_field :person_name, :placeholder => "Enter name"%>
			<%=f.text_field :post_code, :placeholder => "Enter post_code"%>
			<%=f.text_field :address, :placeholder => "Enter address"%>
			<%=f.text_field :valid_telephone_number, :placeholder => "Enter telephone"%>
			<%=f.text_field :email, :placeholder => "Enter email"%>
			<br><br>
			
			<%= f.fields_for :bookable_items, @booking.initialized_removable_items do |b| %>
				<% removable_item = b.object.removable_item %>
		    <%= b.hidden_field :removable_item_id %>

		    	<%= b.check_box :enable %>
		      <%= b.label :enable, removable_item.item_name %>
		      	      
		      <%=b.select :bookable_item_qty, (1..10) %>
		    
		  
			<%end%>
			
			
			
			<%=f.submit%>
			<% @booking.errors.full_messages.each do |msg| %>
    		<li><%= msg.humanize %></li>
  		<% end %>
		<%end%>
	</div>
</div>

app/views/layouts/_footer.html.erb
<div class="container Rdl-footer-address-details">
		<div class="foot-cont-itms">
			<div class="row">
			<div class="col-xs-12 col-sm-12 col-md-4 col-lg-4 col-xl-4">
				<div class="foot-tit">
					<h5 class="foot-tit-txt text-left">
						Head Office
					</h5>

					

					<hr class="foot-thin-line">
				</div>
				<div class="foot-tit-addr rdl-business-address">
					<h5 class="foot-tit-addr-txt foot-tit-add-hed">
						<p class="p-foot-add-one  p-foot-foot-text">24 Gladstone Avenue,</p>
						<p class="p-foot-add-two  p-foot-foot-text">Chester,</p>
						<p class="p-foot-add-three  p-foot-foot-text">Cheshire.</p>
						<p class="p-foot-add-four  p-foot-foot-text">CH1 4JU</p>
					</h5>
				</div>
				<div class="foot-tit-tel">
					<h5 class="foot-tit-tel-txt">
						<p class="p-foot-tel-one p-foot-foot-text">Tel : 07939595187</p>
						<p class="p-foot-tel-two p-foot-foot-text">Email: info@rdlway.com</p>
					</h5>
				</div>
			</div>


			<div class="col-xs-12 col-sm-12 col-md-4 col-lg-4 col-xl-4">
				<div class="foot-tit">
					<h5 class="foot-tit-txt">
						Useful Links
					</h5>
					<hr class="foot-thin-line">
				</div>
				<div class="foot-tit-addr">
					<h5 class="foot-tit-addr-txt text-left">
						<a class=" nav-link  nav-link-nav-links js-scroll-trigger p-foot-useful-one p-foot-foot-text " href="#about-rdl-removals">About Us</a>
						<a class=" nav-link  nav-link-nav-links js-scroll-trigger p-foot-useful-two p-foot-foot-text " href="#rdl-removals-services">Services</a>
						<!-- <p class="p-foot-useful-four p-foot-foot-text data-toggle="modal" data-target="#myModal"">Terms & Conditions</p> -->
						<%#= link_to "#myModal", data: { toggle: "modal" } do %>
						 <!--  <p class="p-foot-useful-four p-foot-foot-text">Terms & Conditions</p> -->
						<%# end %>


						<%= link_to  terms_path,  {'data-toggle' =>  "modal", 'data-target' => '#myModal'} do %>
							<p class="p-foot-useful-four p-foot-foot-text">Terms & Conditions</p>
						<%end%>

						
				
					</h5>
				</div>
				<div class="foot-tit-tel">
					<h5 class="foot-tit-tel-txt">
						<!-- <p class="p-foot-useful-one-btn p-foot-foot-text">Get Free Qoute</p> -->
						<a class="nav-link  nav-link-nav-links js-scroll-trigger p-foot-useful-one-btn p-foot-foot-text" href="#rdl-removals-get-a-free-qoutation">Get a free Qoute</a>
						<!-- <p class="p-foot-useful-two-btn p-foot-foot-text">Book Online</p> -->
						<!-- <a class="nav-link js-scroll-trigger p-foot-useful-two-btn p-foot-foot-text p-foot-foot-text-two" href="#qoute">Book Online</a> -->
					</h5>
				</div>
			</div>

			<div class="col-xs-12 col-sm-12 col-md-4 col-lg-4 col-xl-4">
				<div class="foot-tit">
					<h5 class="foot-tit-txt">
						Social
					</h5>
					<hr class="foot-thin-line">
				</div>
				<div class="foot-tit-addr">
					<h5 class="foot-tit-addr-txt">
						<p class="p-foot-useful-one">
							<%=link_to "https://www.facebook.com/RDLRemovals/" do %>
								<i class="fab fa-facebook-f"></i>
							<%end%>
						</p>
							
						<p class="p-foot-useful-two">
							<%=link_to "https://twitter.com/RdlRemovals" do%>
								<i class="fab fa-twitter"></i>
							<%end%>
						</p>
						
					</h5>
					<!-- <iframe width="100%" height="315" src="https://www.youtube.com/embed/SEfFdhpUsOI" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe> -->
				</div>
				
			</div>
		</div>
		</div>
		<div class="copy-r text-center">
			<hr class="cop-btm-lne">
			<h6 class="foot-copy">&copy; <%=Time.new.year%> R D L Transportation Ltd Reg No. 12105554</h6>
			<div class="counter">
				<!-- Start of CuterCounter Code -->
				<a href="https://www.cutercounter.com/" target="_blank"><img src="https://www.cutercounter.com/hits.php?id=gvqcnfo&nd=9&style=2" border="0" alt="website counter"></a>
				<!-- End of CuterCounter Code -->			                        
			</div>
		</div>
		
	</div>

		<!-- The Modal -->
		  <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLongTitle" aria-hidden="true">
		    <div class="modal-dialog">
		      <div class="modal-content">
		      
		        <!-- Modal Header -->
		        <div class="modal-header">
		          <h1 class="modal-title">Terms & Conditions</h1>
		          <button type="button" class="close" data-dismiss="modal">×</button>
		        </div>
		        
		        <!-- Modal body -->
		        <div class="modal-body">
		          <%=render 'layouts/terms_modal'%>
		        </div>
		        
		        <!-- Modal footer -->
		        <div class="modal-footer text-center foot-modal">
		          <button type="button" class="btn btn-danger cancel-btn" data-dismiss="modal">Close</button>
		          <button type="button" class="btn btn-success danger-btn" data-dismiss="modal">Accept</button>
		        </div>
		        
		      </div>
		    </div>
		  </div>
		  
		</div>
</div>

app/views/layouts/_top_nav.html.erb
<div class="topnav" id="myTopnav">
	<div class="container">
		<div class="top-header-social">	
			<div class="left-info">
				<ul class="left-pane-ul">
					<li class="left-pane-ul-li">
						<span>
							<i class="far fa-clock"></i>
							<strong>MON - Sun 8.00 - 22.00</strong>
						</span>
					</li>

					<li class="left-pane-ul-li mobile-icn">
						<span>
							<i class="fas fa-mobile-alt"></i>
							<strong>07939595187</strong>
						</span>
					</li>
				</ul>

				<div class="mob-so-only">
					<ul class="mob-so-only-ul">
						<li class="mob-so-only-u-li mobile-social-tw">
							<span>
								<%=link_to "https://twitter.com/RdlRemovals" do%>
									<i class="fab fa-twitter"></i>
								<%end%>
							</span>
						</li>

						<li class="mob-so-only-u-li mobile-social-fb">
							<span>
								<%=link_to "https://www.facebook.com/RDLRemovals/" do %>
									<i class="fab fa-facebook-f"></i>
								<%end%>
							</span>
						</li>
					</ul>
				</div>

			</div>
			<div class="right-info">
				<ul class="right-pane-ul">
					<li class="right-pane-ul-li twitter-icn">
						<span>
							<%=link_to "https://twitter.com/RdlRemovals" do%>
								<i class="fab fa-twitter"></i>
							<%end%>
						</span>
					</li>

					<li class="right-pane-ul-li facebk-icn">
						<span>
							<%=link_to "https://www.facebook.com/RDLRemovals/" do %>
								<i class="fab fa-facebook-f"></i>
							<%end%>
						</span>
					</li>
				</ul>
			</div>
		</div>
		<div class="header-mid">
			<div class="logo">
					
				<a class=" nav-link  nav-link-nav-links js-scroll-trigger p-foot-useful-one p-foot-foot-text"  href="#rdl-removals-chester-introduction"><%=image_tag("rdl_logo.svg", class: "logo-image", alt: "Rdl Company Logo")%></a>
					
			</div>

			<div class="slogan-warp">
				<!-- <div class="slogan-wrap-text text-right"> -->
					<ul class="slogan-wrap-ul">
						<li class="slogan-wrap-ul-li nav-btn-get-qoute">
							<%#=link_to "Get a Qoute", "#", class: "geta-qoute-link"%>
							<a class="nav-link js-scroll-trigger geta-qoute-link" href="#rdl-removals-get-a-free-qoutation">Get a Quote</a>
						</li>

						<!-- <li class="slogan-wrap-ul-li nav-btn-bk-online">
							<%#=link_to "Book Online", "#", class: "bk-online-link"%>
						</li> -->
					</ul>
					
					
				<!-- </div>	 -->
			</div>
		</div>
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>R D L Removals </title>
    <%#= display_meta_tags site: '- R D L -' %>
    <%= display_meta_tags description: "Your Local House Removing Partner", keywords: "near me, house rent, house rent near me, chester, west-midlands, stoke-on-trent, stoke, cheap , affordable, rent a car, house removals chester, house removals stoke-on-trent, house removals, house removals costs, house removal companies, house removals london, house removal boxes, house removal costs uk, man with van, man with van london, manwith man stoke-on-trent, man with van chester,man with van near me, man with van hire, man with van delivery service, man with van courier, man with van courier uk"%>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    
    <link href="https://fonts.googleapis.com/css?family=Raleway:700&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Quicksand&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Roboto:900&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Roboto+Condensed&display=swap" rel="stylesheet">
    <%= favicon_link_tag ('favicon.ico') %>
  </head>

  <body>
    <%=render 'layouts/top_nav'%>
    <!-- <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p> -->
    <%= yield %>
    <script src="assets/jquery.easing.min.js"></script>
    <script src="assets/scrolling-nav.js"></script>
  </body>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

</html>

app/views/page/_contact.html.erb
<div class="container contact-us-for-free-qoutation contact-form">
	<div class="req-qte-sec-head">
		<h5 class="req-qt-head-txt">Request A free Qoute</h5>
	</div>
	<hr class="thin-red-line">
	<div class="row">
		<div class="col-md-4 col-lg-4 col-xl-4 quote-explain-cols">
			Would you like to speak to one of our 
			removal advisers over the phone?
			Just submit your details and we will be in touch shortly.
		</div>
		<div class="col-md-8 col-lg-8 col-xl-8">
			<div class="request-qte-frm">
				<%= form_for @contact, url: page_index_path, remote: true do |f| %>
				<div class="form-row">
			    <div class="form-group col-md-6">
			      <!-- <input type="text" class="form-control" id="inputEmail4" placeholder="your Name"> -->
			      <%= f.text_field  :name, required: true, class: "form-control", :placeholder=> "Your Name" %>
			    </div>
			    <div class="form-group col-md-6">
			      <!-- <input type="email" class="form-control" id="inputEmail4" placeholder="Your Email">		 -->
			      <%= f.email_field  :email, required: true, class: "form-control", :placeholder=> "Your Email" %>	    
			    </div>
			  </div>
			  <div class="form-row">
			    <div class="form-group col-md-6">
			     <!--  <input type="text" class="form-control" id="inputEmail4" placeholder="your Phone"> -->
			      <%= f.telephone_field  :phone, required: true, class: "form-control", :placeholder=> "Your Phone" %>
				
			    </div>
			    <div class="form-group col-md-6">
			      <!-- <input type="email" class="form-control" id="inputEmail4" placeholder="Your Postcode">	 -->
			      <%= f.text_field  :post_code, required: true, class: "form-control", :placeholder=> "Your Postcode" %>		      
			    </div>
			  </div>
			  <div class="form-row">
			    <div class="form-group col-md-10">
			      <!-- <textarea class="form-control" id="exampleFormControlTextarea1" rows="3"></textarea> -->
			      <%= f.text_area  :message, required: true, class: "form-control", :placeholder=> "Your Message" , :rows => "3"%>
			    </div>

			    
			    <div class="form-group col-md-2">
			      <button type="submit" class="btn btn-primary btn-tbn">Submit</button>
			    </div>
					
					<div class="hidden">
		        <div class="form-group col-md-12">
				      <%= f.label :nickname %>
			        <%= f.text_field :nickname, :hint => 'Leave this field blank!' %>
			    	</div>
		      </div>
			  </div>
			  <%end%>

			  <div class="col-md-12 " id="flash-message">
			    <%= render 'flash' %>
			  </div>
			</div>
		</div>
	</div>
</div>

app/views/page/_flash.html.erb
<% flash.each do |message_type, message| %>
    <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
<% end %>

app/views/page/create.js.erb
console.log("This is the create.js.erb file");
// Render flash message
$('#contact').html("<%= j render 'contact' %>");
$('#flash-message').html("<%= j render 'flash' %>").delay(3000).fadeOut(4000);

app/views/page/terms.js.erb
$("#myModal").html("<%= escape_javascript(render 'page/terms') %>");
// $(".modal-body").html("<%= escape_javascript(render 'layouts/terms_modal') %>");
$("#myModal").modal();